
model:
  cols_target: ['goal1','goal21','goal22','goal23','goal24','goal25',]
  col_id: 'orderid'
  col_client: 'userid'
  cols_cat: 'auto'
  cv_byclient: True
  n_splits: 3
  n_repeats: 1

lightgbm:
  params:
    bagging_fraction: 0.849285747554019
    bagging_freq: 5
    bagging_seed: 0
    boosting_type: 'gbdt'
    data_random_seed: 0
    drop_seed: 0
    feature_fraction: 0.8212766928844304
    feature_fraction_seed: 0
    lambda_l1: 0.8955546599539566
    lambda_l2: 1.4423261095989717
    learning_rate: 0.03
    max_bin: 255
    max_depth: 43
    metric: auc
    min_data_in_leaf: 149
    min_sum_hessian_in_leaf: 1.804477623298885
    num_leaves: 363
    objective: binary
    seed: 0
    verbose: -1
  numboost: 228
